### PR TITLE
Sync with upstream branch

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by vuntz** [comment]
@matelakat maybe we'll want to wait for https://github.com/SUSE-Cloud/cookbook-openstack-network/pull/22 to be merged upstream first?

**Comment by matelakat** [comment]
@vuntz yes, that would be nice.

**Review by matelakat — APPROVED** [review]
@vuntz change merged!

**Review by matelakat — CHANGES_REQUESTED** [review]
Ah, sorry, that means we need the term handler as well - changing my review to -1 then

**Comment by vuntz** [comment]
@matelakat I added the commits here, please re-review :-)

**Review by matelakat — APPROVED** [review]

**Comment by matelakat** [comment]
Let's merge #6 instead, that's a later sync.

**Pull request closed without merging**
